### ISSUE TITLE
Implement Going Forward

### ISSUE THREAD

**Issue by saresend** [saresend/selenium-rs#5] opened 2018-09-11 23:19 UTC

**Comment by lazypassion** [comment] 2019-02-12 00:48
How can I help with this?

**Comment by saresend** [comment] 2019-02-12 03:46
Absolutely! It'll be pretty similar to implementing going backward, here: https://github.com/saresend/selenium-rs/blob/2fd853e646269a07d0a6be7787e134c5bd4945bf/src/webdriver.rs#L150, and then in general I've been following that pattern, as well as the docs for webdriver clients, found here: https://www.w3.org/TR/webdriver1/#forward. 

Effectively what is happening is that we are making a request to the WebDriver server, that will then execute our request and update the state of the browser, so all you really need to be doing is making that request! 

Let me know if you have any other questions!

**Comment by lazypassion** [comment] 2019-02-21 16:48
Is there anyway to test the code to verify the new function didn't magically break anything? Or a way to confirm the added code works as intended?

**Comment by globalworming** [comment] 2020-08-31 08:18
this was fixed in #19 , can be closed

**Closed** 2020-09-01 00:50 UTC
Labels: good first issue, help wanted
